У завданнях 1-4. Вам наданий простий код на Python, який не відповідає вказівкам PEP8. Ваше завдання — відредагувати код так, аби він відповідав PEP8. Напишіть після редагуванню коду, дотримання яких правил з pep8 ви досягли в відредагованій версі, наприклад
```
- додала пробіли навколо бінарного оператора
- додала два порожні рядки між визначеннями функцій
і тд
```
Також можна зазанчити використані правила коментарями по коду, а не окремим повідомленням.

Відредагований код має виконувати весь той самий функціонал, але бути написаний відповідно до вимог до гарного коду на Python! Не забудьте запустити відредагований код, він має бути робочим.

Завдання 1.

In [1]:
def greet(name):print(f"Hello, {name}")
def add(n1,n2):return n1+n2

x = 5;y = 3
display(greet("John"),add(x,y))

Hello, John

None

8

In [2]:
def greet(name):
    print(f"Hello, {name}")


def add(n1, n2):
    return n1 + n2


x = 5
y = 3

display(greet("John"), add(x,y))

Hello, John

None

8

- між визначеннями функції додала по два порожні рядки
- оформила кожний рядок функцій з нового рядку
- оператори '=' та '+' відокремлені пробілами
- додала пробіли після коми
- print та return поставила під назвою функцій
- кожна змінна визначена з нового рядка

Завдання 2.

In [3]:
from math import *
def calcArea(r):return pi*r**2
def calcCircumference(r):return 2*pi*r

radius=5
print("Area:",calcArea(radius),"Circumference:",calcCircumference(radius))

Area: 78.53981633974483 Circumference: 31.41592653589793

In [4]:
from math import pi


def calc_area(r):
    return pi * r ** 2


def calc_circumference(r):
    return 2 * pi * r


radius = 5

print("Area:",calc_area(radius),"Circumference:",calc_circumference(radius))

Area: 78.53981633974483 Circumference: 31.41592653589793

- імпортувала тільки pi з пакету math, а не весь пакет
- виправила назви функції
- між визначеннями функції додала по два порожні рядки
- оформила кожний рядок функцій з нового рядку
- return поставила під назвою функцій
- оператори '=' та '*' відокремлені пробілами

Завдання 3.

In [5]:
class animal: pass
class dog(animal):
    def __init__(self,name):
        self.name=name
        self.type='Dog'

In [6]:
class Animal:
  pass


class Dog(Animal):
    def __init__(self, name):
        self.name = name
        self.type = 'Dog'

- назви класів починаються з великої букви
- pass з нового рядка
- додала між класами по два порожні рядки
- оператори '=' відокремлений пробілами
- додала пробіл після коми в параметрах

Завдання 4.

In [7]:
list=[1,2,3,4,5]
for i in range(len(list)):print(list[i])

1
2
3
4
5

In [8]:
my_list = [1, 2, 3, 4, 5]

for i in my_list:
  print(i)

1
2
3
4
5

- перейменувала список, так як list - це вбудована функція пайтон
- оператор '=' відокремлений пробілами
- після ком пробіли
- пустий рядок між циклом і списком
- спростили код циклу for

5.У вас є DataFrame df, що представляє результати тестів студентів з математики, англійської мови та історії. Поточний код обчислює середній бал для кожного студента шляхом ітерації за рядками DataFrame за допомогою iterrows().

Ваше завдання полягає в тому, щоб змінити код так, аби уникнути використання iterrows() і замість цього застосувати більш ефективне та читабельне рішення відповідно до правил, озвучених у лекції. Рефакторинг треба зробити лише частині, де рахуються середні, імпорт і визначення датафрейму лишаємо без змін.

In [9]:
import pandas as pd

df = pd.DataFrame({
    'student': ['Alice', 'Bob', 'Charlie', 'David'],
    'math_score': [89, 94, 77, 85],
    'english_score': [92, 88, 79, 85],
    'history_score': [84, 92, 81, 89]
})

In [10]:
averages = []
for _, row in df.iterrows():
    averages.append((row['math_score'] + row['english_score'] + row['history_score']) / 3)

df['average_score'] = averages

In [11]:
df['average_score'] = df.select_dtypes('number').mean(axis=1)

In [12]:
df

   student  math_score  english_score  history_score  average_score
0    Alice          89             92             84      88.333333
1      Bob          94             88             92      91.333333
2  Charlie          77             79             81      79.000000
3    David          85             85             89      86.333333

6.У Вас є великий DataFrame df, що представляє транзакції продажу в магазині. Цей DataFrame містить понад 1 мільйон рядків і кілька стовпців, зокрема «product_name», «product_category», «product_price» і «transaction_date».

І «product_name», і «product_category» є рядками, що представляють численні, але обмежені унікальні назви продуктів і категорії відповідно.

Напишіть код для ефективного перетворення стовпців «product_name» і «product_category» на категорійний тип для ефективного використання пам’яті.
Спробуйте вирішити це завдання, мінімізуючи використання пам'яті та зберігаючи читабельність коду. Крім того, виміряйте використання пам’яті до та після перетворення, щоб продемонструвати підвищення ефективності.

Порівняйте кількість памʼяті, яку займає наданий набір даних і новий, створений Вами. В лекції був приклад. В скільки разів менше памʼяті займає новий датафрейм?

In [13]:
import pandas as pd
import numpy as np

np.random.seed(0)

products = ['apple', 'banana', 'cherry', 'dates', 'elderberry']
categories = ['fruit', 'fruit', 'fruit', 'fruit', 'fruit']

N_ROWS = 10**6
df = pd.DataFrame({
    'product_name': np.random.choice(products, N_ROWS),
    'product_category': np.random.choice(categories, N_ROWS),
    'product_price': np.random.uniform(1, 10, N_ROWS),
    'transaction_date': pd.date_range(start='1/1/2000', periods=N_ROWS, freq='h')
})

In [14]:
df_memory = df.memory_usage(index=False).sum()

df_memory

np.int64(32000000)

In [15]:
for col in df[['product_name', 'product_category']]:
  df[col] = pd.Categorical(df[col])

df_memory_cat = df.memory_usage(index=False).sum()
df_memory_cat

np.int64(18000328)

In [16]:
dif_memory = df_memory / df_memory_cat

In [17]:
print(f"Новий датафрейм займає в {dif_memory:.2f} разів менше пам'яті.")

Новий датафрейм займає в 1.78 разів менше пам'яті.

7.В цьому завданні кілька пунктів. Треба виконати усі послідовно.   
    7.1. Завантажте дані у pandas dataframe з файла `ecommerce_data.csv`. Обовʼязково при завантаженні вкажіть параметр `encoding = 'ISO-8859-1'`, без нього буде помилка.  
    7.2. Заповніть пропущені значення в колонці CustomerID на -1 та перетворіть тип цієї колонки на str, адже зараз вона типу float, а це не правильний тип даних для ідентифікатора клієнта.  
    7.3. З допомогою бібліотеки sweetviz побудуйте html звіт, який порівнює дані для країни "Germany" і країни "France". У Вас можуть виникнути багато попереджень (Warning), їх рекомендую вимкнути наступним шматком коду   
    
   
    import warnings

    with warnings.catch_warnings(record=True):
        # your code
    
    
   7.4.Напишіть 5 відмінностей для двох зазначених країн на основі побудованого звіту, без виконання додаткового аналізу іншими інструментами.

In [18]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [19]:
# 7.1 Завантажуємо дані
path = 'drive/MyDrive/Date_Analysis/data/ecommerce_data.csv'
df = pd.read_csv(path, encoding='ISO-8859-1')

In [20]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [21]:
# 7.2 Заповнюємо пропущені значення та перетворюємо тип колонки
df['CustomerID'] = df['CustomerID'].fillna(-1).astype(str)

In [22]:
! pip install -q sweetviz

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.1/15.1 MB 76.0 MB/s eta 0:00:00

In [23]:
# 7.3 Побудуємо html звіт за допомогою бібліотеки sweetviz
import sweetviz as sv

compare_report = sv.compare(
    [df[df.Country == 'Germany'], 'Germany'],
    [df[df.Country == 'France'], 'France']
)
compare_report.show_html('sv_compare_report.html')

                                             |          | [  0%]   00:00 -> (? left)

Report sv_compare_report.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

1. Більше замовлень зробили клієнти з Німеччини - 603 замовлення, а клієнти з Франції зробили 461 замовлення.
2. З Німеччини маємо більше клієнтів - 95, у Франції 88 клієнти.
3. Цікаво, що більшу виручку ми отримали у Франції 43032, у Німеччині ж - 37666.
4. Кількісно більше деталей продали клієнтам з Німеччини 117К, клієнти з Франції придбали в сумі 110К деталей.
5. У Німеччині клієнти придбали більше різноманітних деталей - 1671 шт, у Франції - 1543 шт різних видів.

8.З допомогою ChatGPT виявіть, чи є та які помилки в наступному коді.  
Попросіть після цього переписати код із дотриманням PEP8. Проаналізуйте результат. Чи справді ChatGPT виправив всі стилістичні помилки? Якщо ні, напишіть йому ще кілька запитів, аби код відповідав вимогам PEP8.  
Вставте фінальну версію коду з чату у ноутбук та запустіть на заданому списку. Має вертатись 50.  
Напишіть, які промпти (інструкції) при зверненні до ChatGPT ви застосували та додайте скріншот(-и) з промптами та відповідями чата.  
Якщо зробили висновки при виконанні цього завдання, то діліться також :)

**ЯК ВСТАВИТИ СКРІНШОТ в Jupyter Notebook** :
1. Створіть нову Markdown клітинку
2. В новоствореній клітинці обираєте в меню Jupyter Notebook Edit -> Insert Image
3. Обираєте картинку
4. В клітинці має зʼявитись текст, який містить картинку. Запустіть клітинку.

Або можна просто перетягнути картинку в Markdown клітинку.

In [24]:
def CalculateVariance(nl):
    sum_list = 0
    for n in nl:
        sum_list = sum_list + n
    mean = sum_list / len(nl)
    sum_squares = 0
    for n in nl:
        sum_squares = sum_squares + n**2
    mean_squares = sum_squares / len(nl)
    return mean_squares

In [25]:
input_list = [75, 80, 85, 90, 95]

In [26]:
def calculate_variance(numbers):
    if len(numbers) == 0:
        raise ValueError("Список не може бути порожнім")

    total_sum = 0
    for number in numbers:
        total_sum += number

    mean = total_sum / len(numbers)

    sum_of_squares = 0
    for number in numbers:
        sum_of_squares += number ** 2

    mean_of_squares = sum_of_squares / len(numbers)

    variance = mean_of_squares - mean ** 2

    return variance

In [27]:
calculate_variance(input_list)

50.0

Застосовані промпти:
- Чи є в коді помилки? Якщо є, то які?
- Ти можеш переписати код з дотриманням правил PEP8?